### ISSUE TITLE
plugin not found at rubygems.org

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-mongodb#1]
My recipe looks like this
```
sensu_gem 'sensu-plugins-mongodb' do
  options('--prerelease')
  version '0.0.1.alpha.1'
end

# MongoDB

sensu_check "mongodb" do
  command "check_mongodb.py"
  handlers ["default"]
  standalone true
  interval 60
end
```

But the plugin hasn't been pusblished to rubygems?
```
  * sensu_gem[sensu-plugins-mongodb] action install (up to date)
  * gem_package[sensu-plugins-mongodb] action install[2015-03-05T12:45:34+00:00] WARN:  failed to find gem sensu-plugins-mongodb (= 0.0.1.alpha.1) from [https://rubygems.org/]
```

**Comment by mattyjones** [comment]
The gems are created based upon time and the state of the code.  If you need a gem right now, you could use the gemspec in the repo as a starting point and build it yourself.  As far as when an official gem will be available, we will try and get to this one sooner since it is requested.

Thanks
