### ISSUE TITLE
Proper check-mongo.py installation

### ISSUE THREAD

**Issue by z0rc** [sensu-plugins/sensu-plugins-mongodb#14]
Fix in #13 didn't work as expected. It creates `/opt/sensu/embedded/bin/check-mongodb.py`, but its contents are just regular Gem loader.

I'm not a Ruby guy, can someone more experienced take a look into this?

**Comment by mattyjones** [comment]
@z0rc  @analytically 

It looks like it created a bunstub. I can fix it to not create a bunstub but you will need to call that python file from the bin directory where the gem is installed. Non-ruby files will not get dropped into the sensu embedded ruby bin directory. The gem stuff works best with Ruby for obvious reasons, anything non-ruby gets dicy. There are a few ways to solve this, a generic shell wrapper would work but I don't have the ability atm to write one.

I am open to possible suggestions on ways to do this simpler. To get the functionality of a cross-language env you really should be using a language agnostic release method such as RPM, TGZ, or DEB. As of right now those methods are outside of the scope of the project but I have been thinking about doing a stock tarball deployable released from github for each repo. The first time I could devote serious effort to that would be a few months but it has been talked about.

**Comment by z0rc** [comment]
Probably something like [this](https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/bin/check-memory-percent.rb) could be implemented here too. I would really like to have gem installation to work out of the box, this mechanism is used by [docker-sensu runtime plugin installation](https://github.com/sstarcher/docker-sensu/blob/master/bin/install). There is a [PR](https://github.com/sstarcher/docker-sensu/pull/3) to mitigate this issue too. It's very convenient to use just script name in check detention rather then the full path.

**Comment by mattyjones** [comment]
@z0rc  If you would like to take stab at this I would be happy to merge it.

**Comment by kpmueller** [comment]
I also have encountered this and would appreciate a fix. At least in 0.0.6, the .py file exists, but I have to call it directly in the gem directory. :)

**Comment by analytically** [comment]
I've just pushed a ruby wrapper.

**Comment by eheydrick** [comment]
We just got to release a new version with the wrapper and you should be all set.

**Comment by law** [comment]
Any word on this?  I'm unable to get this working on a Sensu client running Ubuntu 14.04.3 against Mongo 3.0.8

**Comment by eheydrick** [comment]
Stay tuned, new release hopefully out soon.

**Comment by eheydrick** [comment]
Version 0.0.8 is out with a ruby wrapper. Note you will need to install the `pymongo` python package as well.
