### ISSUE TITLE
Metric check for "mongostat" utility 

### ISSUE THREAD

**Issue by tanaysoni** [sensu-plugins/sensu-plugins-mongodb#17]
<a href = "https://docs.mongodb.org/manual/reference/program/mongostat/" > mongotop</a> utility provides useful collection and db level metrics that could be stored in a Graphite or other time series database. We could write a Sensu plugin that parses the JSON output of `mongostat` and construct metrics that can be relayed by Sensu handlers. 

Once we've some inputs, I'd be happy to contribute in writing/testing a Python script to do the job.

**Comment by tanaysoni** [comment]
I found a <a href="https://github.com/y13i/sensu-plugin-metrics-mongostat/blob/master/metrics-mongostat.rb">plugin</a> to do exactly this, however getting an error.

**Comment by eheydrick** [comment]
Looks like you got that plugin working. Would be nice to have that one contributed the community plugins.
