### ISSUE TITLE
Installing ruby gem doesn't copy along python binary

### ISSUE THREAD

**Issue by brendangibat** [sensu-plugins/sensu-plugins-mongodb#23]
The problem is on: https://github.com/sensu-plugins/sensu-plugins-mongodb/blob/master/sensu-plugins-mongodb.gemspec#L25

Can you include *.py in the executables globbed?

**Comment by eheydrick** [comment]
Due to a limitation with rubygems, ruby binstubs do not get created properly for non-ruby files. For that reason there's a ruby wrapper for the python script, `check-mongodb.rb`, that you exec instead of the python script.

**Comment by brendangibat** [comment]
I was calling the .rb file after installing the gem with `gem install --no-ri --no-rdoc --no-wrapper sensu-plugins-*.gem` after a `gem build`, unfortunately only the .rb gets copied to the ruby bin directory so the file path from [https://github.com/sensu-plugins/sensu-plugins-mongodb/blob/master/bin/check-mongodb.rb#L3](the rb file) won't find the .py file.
