### ISSUE TITLE
"lock" check doesn't work with Mongo 3.2

### ISSUE THREAD

**Issue by furbiesandbeans** [sensu-plugins/sensu-plugins-mongodb#25]
The data['globalLock']['lockTime'] variable doesn't exist on 3.2

**Comment by eheydrick** [comment]
Can you try with the latest release 1.0.0, it added support for MongoDB 3.2. Let us know if you're still having problems.

**Comment by eheydrick** [comment]
Hey @furbiesandbeans were you able to try the latest release?

**Comment by eheydrick** [comment]
Feel free to reopen this issue if it's still an issue.

**Comment by yuganghu** [comment]
I don't think the line was changed in any of the releases (check_mongodb.py).
